#!/bin/bash

python porosity_sensitivity_test.py "1" "2" 
python porosity_sensitivity_test.py "1" "3" 
python porosity_sensitivity_test.py "1" "4" 
python porosity_sensitivity_test.py "2" "2" 
python porosity_sensitivity_test.py "2" "3" 
python porosity_sensitivity_test.py "2" "4"
python porosity_sensitivity_test.py "2" "5"
python porosity_sensitivity_test.py "3" "2"   
python porosity_sensitivity_test.py "3" "3"
python porosity_sensitivity_test.py "3" "4"  
python porosity_sensitivity_test.py "3" "5" 
python porosity_sensitivity_test.py "45" "2"
python porosity_sensitivity_test.py "45" "3"
python porosity_sensitivity_test.py "45" "4" 
python porosity_sensitivity_test.py "45" "7"
python porosity_sensitivity_test.py "45" "8"
python porosity_sensitivity_test.py "45" "9"
python porosity_sensitivity_test.py "45" "10"      
# python porosity_sensitivity_test.py "89" "2"
# python porosity_sensitivity_test.py "89" "3"
# python porosity_sensitivity_test.py "89" "4" 
# python porosity_sensitivity_test.py "89" "7"
# python porosity_sensitivity_test.py "89" "8"
# python porosity_sensitivity_test.py "89" "9"
# python porosity_sensitivity_test.py "89" "10"    
python porosity_sensitivity_test.py "1011" "2"
python porosity_sensitivity_test.py "1011" "3"
python porosity_sensitivity_test.py "1011" "4" 
python porosity_sensitivity_test.py "1011" "7"
python porosity_sensitivity_test.py "1011" "8"
python porosity_sensitivity_test.py "1011" "9"
python porosity_sensitivity_test.py "1011" "10"
python porosity_sensitivity_test.py "12" "2"

